import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:iventure001/Widgets/NavigationBar.dart';
import 'package:iventure001/Widgets/TextFieldWidget.dart';
import '../../../Widgets/HeadBackButton.dart';
import 'package:iventure001/Data/BlitzCanvasContent/BcFrameworkData.dart';
import 'package:iventure001/Widgets/CompleteStepButton.dart';

class BcConsumerTouchPoints extends StatefulWidget {
  @override
  _BcConsumerTouchPointsState createState() => _BcConsumerTouchPointsState();
}

var keyTouchLabelColor = Color(0XFF919191);
bool validKeyTitle = true;
final keyTouchTextController = TextEditingController();
final keyTouchFocusNode = new FocusNode();
String keyTouchText;

var capitalizeLabelColor = Color(0XFF919191);
bool validCapitalize = true;
final capitalizeTextController = TextEditingController();
final capitalizeFocusNode = new FocusNode();
String capitalizeText;

var growthLabelColor = Color(0XFF919191);
bool validGrowth = true;
final growthTextController = TextEditingController();
final growthFocusNode = new FocusNode();
String growthText;

class _BcConsumerTouchPointsState extends State<BcConsumerTouchPoints> {
//  NotifyProgress() {
//    setState(() {
//      bcpData[0].CompletionValidator = false;
//      print(bcpData[0].CompletionValidator);
//    });
//  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0XFFFAFAFA),
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(60.0),
        child: NavigationBar(),
      ),
      body: Center(
        child: Container(
          //height: MediaQuery.of(context).size.height * .40,
          margin: EdgeInsets.only(top: 40.0),
          width: MediaQuery.of(context).size.width * .40,
          decoration: BoxDecoration(
            color: Colors.white,
            //shape: BoxShape.rectangle,
            boxShadow: [
              BoxShadow(
                color: Colors.grey,
                offset: Offset(0.0, 1.0), //(x,y)
                blurRadius: 2.0,
              ),
            ],
          ),
          child: SingleChildScrollView(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 40),
              child: Column(
                children: <Widget>[
                  Padding(
                      padding: EdgeInsets.symmetric(vertical: 10.0),
                      child: Text(
                        "The Customer Touchpoints",
                        style: TextStyle(
                            fontSize: 22, fontWeight: FontWeight.bold),
                        textAlign: TextAlign.center,
                      )),
                  TextFieldWidget(
                    labelText: 'What is the key touchpoint you wish to capitalize on?',
                    myTextController: keyTouchTextController,
                    myFocusNode: keyTouchFocusNode,
                    validText: validKeyTitle,
                    maxLines: 1,
                    textCollecter: keyTouchText,
                    helperText: '',
                    labelcolour: keyTouchLabelColor,
                  ),
                  TextFieldWidget(
                    labelText:
                    'How do you intend to capitalize on this touchpoint?',
                    myTextController: capitalizeTextController,
                    myFocusNode: capitalizeFocusNode,
                    validText: validCapitalize,
                    maxLines: 3,
                    textCollecter: capitalizeText,
                    helperText: '',
                    labelcolour: capitalizeLabelColor,
                  ),
                  TextFieldWidget(
                    labelText: 'How much growth do you expect to be generated by this activity on this touchpoint?',
                    myTextController: growthTextController,
                    myFocusNode: growthFocusNode,
                    validText: validGrowth,
                    maxLines: 3,
                    textCollecter: growthText,
                    helperText: '',
                    labelcolour: growthLabelColor,
                  ),
                  Padding(
                    padding: const EdgeInsets.all(30.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        headBackButtton(),
                        SizedBox(
                          width: 50,
                        ),
                        CompleteStepButton(
                          OnTap: () {
                            bcStepsContent[3].bcCompletionValidator = true;
                            Navigator.pushNamed(
                                context, '/BCHomeView');
                          },
                        ),
                      ],
                    ),
                  )
                ],
              )),
        ),
      ),
    );
  }
}
